---
- name: Deploy common firewall
  hosts: all
  become: true
  tasks:
    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: present
    - name: Reset firewall fules
      ansible.builtin.shell: ufw --force reset
    - name: Make sure output are allow by default
      community.general.ufw:
        state: enabled
        direction: outgoing
        policy: allow
    - name: Make sure input are drop by default
      community.general.ufw:
        state: enabled
        direction: incoming
        policy: deny
    - name: Allow SSH
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp
    - name: Allow http
      community.general.ufw:
        rule: allow
        port: http
    - name: Allow https
      community.general.ufw:
        rule: allow
        port: https
    - name: Allow domain-s tcp
      community.general.ufw:
        rule: allow
        port: domain-s
        proto: tcp
    - name: Allow domain-s udp
      community.general.ufw:
        rule: allow
        port: domain-s
        proto: udp
    - name: Disable logging
      community.general.ufw:
        logging: off
    - name: Allow all access from RFC1918 networks to this host
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
      loop:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
