---
nginx_config_debug_output: true
nginx_config_cleanup: true
nginx_config_cleanup_paths:
  - directory:
      - /etc/nginx/conf.d
    recurse: true
nginx_config_selinux: true
nginx_config_selinux_tcp_ports:
  - 80
  - 443

nginx_config_upload_ssl_enable: true
nginx_config_upload_ssl_crt:
  - src: molecule/common/files/ssl/molecule.crt
    dest: /etc/ssl/certs
    backup: true
nginx_config_upload_ssl_key:
  - src: molecule/common/files/ssl/molecule.key
    dest: /etc/ssl/private
    backup: true

nginx_config_main_template_enable: true
nginx_config_main_template:
  template_file: nginx.conf.j2
  deployment_location: /etc/nginx/nginx.conf
  backup: true
  config:
    main:
      load_module:
        - modules/ngx_http_js_module.so
      user:
        username: nginx
      worker_cpu_affinity:
        auto: true
      worker_priority: 0
      worker_processes: auto
      worker_rlimit_core: 10000
      worker_rlimit_nofile: 10000
      worker_shutdown_timeout: 30m
      error_log:
        - /var/log/nginx/ansible.log
        - file: /var/log/nginx/molecule.log
        - file: /var/log/nginx/error.log
          level: notice
      pid: /var/run/nginx.pid
      daemon: true
      debug_points: abort
      env:
        variable: PERL5LIB
        value: /data/site/modules
      lock_file: /var/run/nginx.lock
      master_process: true
      pcre_jit: false
      thread_pool:
        - name: default
          threads: 32
          max_queue: 65536
        - name: molecule
          threads: 32
      timer_resolution: 1s
      working_directory: /etc/nginx
    events:
      accept_mutex: false
      accept_mutex_delay: 500ms
      multi_accept: false
      use: epoll
      worker_aio_requests: 32
      worker_connections: 512
    http:
      include:
        - /etc/nginx/conf.d/*.conf
        - /etc/nginx/conf.d/backend/*.conf
    stream:
      include:
        - /etc/nginx/conf.d/streams/*.conf

nginx_config_status_enable: true
nginx_config_status_backup: true
nginx_config_status_port: 8080
nginx_config_status_access_log:
  path: /var/log/nginx/access.log

nginx_config_http_template_enable: true
nginx_config_http_template:
  - template_file: http/default.conf.j2
    backup: true
    deployment_location: /etc/nginx/conf.d/main.conf
    config:
      core:
        absolute_redirect: true
        aio:
          threads: true
        aio_write: false
        auth_delay: 0s
        chunked_transfer_encoding: true
        client_body_buffer_size: 8k
        client_body_in_file_only: false
        client_body_in_single_buffer: false
        client_body_temp_path:
          path: /var/cache/nginx/client
          level: 2
        client_body_timeout: 60s
        client_header_buffer_size: 1k
        client_header_timeout: 60s
        client_max_body_size: 1m
        connection_pool_size: 256
        default_type: application/octet-stream
        directio: false
        directio_alignment: 512
        disable_symlinks:
          check: "on"
          from: $document_root
        error_page:
          - code:
              - 404
            response: 404
            uri: /404.html
        etag: true
        if_modified_since: exact
        ignore_invalid_headers: true
        internal: false
        keepalive_disable: msie6
        keepalive_requests: 1000
        keepalive_time: 1h
        keepalive_timeout:
          timeout: 75s
          header_timeout: 75s
        large_client_header_buffers:
          number: 4
          size: 8k
        limit_rate: 0
        limit_rate_after: 0
        lingering_close: true
        lingering_time: 30s
        lingering_timeout: 5s
        log_not_found: true
        log_subrequest: false
        max_ranges: 0
        merge_slashes: true
        msie_padding: true
        msie_refresh: false
        open_file_cache:
          max: 10
          inactive: 60s
        open_file_cache_errors: false
        open_file_cache_min_uses: 1
        open_file_cache_valid: 60s
        output_buffers:
          number: 2
          size: 32k
        port_in_redirect: true
        postpone_output: 1460
        read_ahead: 0
        recursive_error_pages: false
        request_pool_size: 4k
        reset_timedout_connection: false
        resolver:
          address: 8.8.8.8
          valid: 60s
          ipv6: false
        resolver_timeout: 30s
        root: html
        satisfy: all
        send_timeout: 60s
        sendfile: false
        sendfile_max_chunk: 0
        server_name_in_redirect: false
        server_names_hash_bucket_size: 32
        server_names_hash_max_size: 512
        server_tokens: true
        subrequest_output_buffer_size: 4k
        tcp_nodelay: true
        tcp_nopush: false
        types:
          - mime: text/html
            extensions: html
          - mime: application/octet-stream
            extensions:
              - bin
              - exe
              - dll
        types_hash_bucket_size: 64
        types_hash_max_size: 1024
        underscores_in_headers: false
        variables_hash_bucket_size: 64
        variables_hash_max_size: 1024
      proxy:
        set_header:
          - field: Host
            value: $proxy_host
          - field: Connection
            value: close
        socket_keepalive: false
      gunzip:
        enable: true
        buffers:
          number: 32
          size: 4k
      gzip:
        enable: true
        buffers:
          number: 32
          size: 4k
        comp_level: 1
        disable:
          - '"msie6"'
        http_version: 1.1
        min_length: 20
        proxied:
          - expired
        vary: false
      headers:
        add_headers:
          - name: Strict-Transport-Security
            value: '"max-age=15768000; includeSubDomains"'
            always: true
        add_trailers:
          name: Strict-Transport-Security
          value: '"max-age=15768000; includeSubDomains"'
          always: false
        expires:
          modified: true
          time: 12h
      log:
        access:
          - path: /var/log/nginx/access.log
        error_log:
          file: /var/log/nginx/error.log
          level: notice
        open_log_file_cache:
          max: 1000
          inactive: 20s
          min_uses: 2
          valid: 1m
      custom_directives:
        - server {}
      upstreams:
        - name: doh_proxy
          keepalive: 32
          least_conn: true
          servers:
            - address: 127.0.0.1:8453
        - name: dot_proxy
          keepalive: 32
          least_conn: false
          servers:
            - address: 127.0.0.1:8953

  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/default.conf
    backup: true
    config:
      servers:
        - core:
            aio:
              threads: default
            keepalive_timeout: 75s
            listen:
              - port: 443
                default_server: true
              - port: "[::]:443"
                default_server: true
            open_file_cache: false
            server_name:
              - localhost
              - "_"
              - voyager-01.mahyuddin.web.id
              - www.mahyuddin.web.id
              - mahyuddin.web.id
            try_files:
              files: $uri
              uri: /images/default.gif
          log:
            access:
              - path: /var/log/nginx/default-access.log
            error:
              - file: /var/log/nginx/error.log
          locations:
            - location: /
              core:
                root: /usr/share/nginx/html
                index: index.html
          ssl:
            certificate: /etc/letsencrypt/live/mahyuddin.web.id/fullchain.pem
            certificate_key: /etc/letsencrypt/live/mahyuddin.web.id/privkey.pem
            session_tickets: false
            protocols:
              - "TLSv1.2"
              - "TLSv1.3"
            dhparam: "/etc/ssl/dhparams.pem"
            ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
          custom_directives:
            - "add_header Strict-Transport-Security max-age=31536000;"
            - "include /etc/nginx/custom.d/cf-allow-ips.conf;"
        - core:
            aio:
              threads: default
            keepalive_timeout: 75s
            listen:
              - port: 80
                default_server: true
            open_file_cache: false
            server_name:
              - localhost
              - "_"
              - voyager-01.mahyuddin.web.id
              - www.mahyuddin.web.id
              - mahyuddin.web.id
            try_files:
              files: $uri
              uri: /images/default.gif
          log:
            access:
              - path: /var/log/nginx/default-access.log
            error:
              - file: /var/log/nginx/error.log
          locations:
            - location: /
              core:
                root: /usr/share/nginx/html
                index: index.html
          rewrite:
            return:
              code: 301
              url: 'https://$host$request_uri'
          custom_directives:
            - "add_header Strict-Transport-Security max-age=31536000;"
            - "include /etc/nginx/custom.d/cf-allow-ips.conf;"
