---
name: CI
on:
  pull_request:
  push:
    branches:
      - master
env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'
  HOST_KEY_CHECKING: false

jobs:
  test_run:
    name: Ansible
    runs-on: [ "vm-ssd" ]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ansible Hello
        run: ansible -m ping -i inventory all
